language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g jsdoc
script:
  - bower install
  - grunt test
  - grunt build
notifications:
  email:
    - dannybluedesign@gmail.com
