language: node_js
node_js:
  - '0.12.2'
install:
  - npm install -g grunt-cli
  - npm install -g bower
script:
  - npm install
  - bower install
  - grunt test
  - grunt
notifications:
  email:
    - dannybluedesign@gmail.com